# Generated by Django 4.2.3 on 2023-07-23 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_alter_invitecard_expiration_date_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ManyToManyField(related_name='more_image', to='games.image', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 14, 20, 12, 53020), verbose_name='дата истечения'),
        ),
    ]
