# Generated by Django 4.2.3 on 2023-07-23 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_image_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ManyToManyField(related_name='more_images', to='games.image', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 22, 15, 19, 4, 37761), verbose_name='дата истечения'),
        ),
    ]
